require: rubocop-minitest

AllCops:
  SuggestExtensions: false
  Exclude:
    - 'temp/*.rb'
    - 'liquid_transpiler.gemspec'
    - 'test/examples/*.rb'

Naming/MethodName:
  Exclude:
    - 'lib/liquid_transpiler.rb'
    - 'lib/liquid_transpiled_methods.rb'

Metrics/MethodLength:
  Max: 35

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Max: 5

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 500

Naming/FileName:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  AutoCorrect: always

Style/GuardClause:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false
