require: rubocop-minitest

AllCops:
  SuggestExtensions: false
  Exclude:
    - 'temp/*.rb'

Naming/MethodName:
  Exclude:
    - 'lib/liquid-transpiler.rb'
    - 'lib/liquid-transpiled-methods.rb'

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 5

Metrics/ClassLength:
  Max: 300

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false
