require: rubocop-minitest

AllCops:
  SuggestExtensions: false
  Exclude:
    - 'temp/*.rb'

Naming/MethodName:
  Exclude:
    - 'lib/liquid-transpiler.rb'
    - 'lib/liquid-transpiled-methods.rb'

Metrics/MethodLength:
  Max: 30

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Style/GuardClause:
  Enabled: false
